#!/usr/bin/env python3
"""Generate or check `registry/kit.json` — the reference manifest of the shipped kit.

WHAT THIS IS FOR. A member factory's drift was previously unmeasurable: the only
thing that could say whether a factory's copy of `tools/ledger.py` matched the
template's was a person reading both trees. Measured 2026-09-25 over the ten
bootstrap-named files across five member factories: **50 cells, 1 identical
(2%), 20 drifted, 29 absent** -- and three of the absent ones were the write-path
guards (`tools/gate_budget.py` and both `tools/hooks/` refusal points), which had
therefore never bound a single member. Without a manifest a drift leg can only
say that a factory DIFFERS; it cannot say what it is missing or what the
reference is. This file is that reference.

THE SET IS THE TREE, NOT A LIST. The manifest covers every file under
`TEMPLATE/` except transient build artifacts, because a hand-maintained list of
shipped files is a second copy of the tree that goes stale silently -- the class
this factory has ruled against repeatedly. A file added to `TEMPLATE/` appears in
the manifest on the next regeneration, and `--check` FAILS until it does, so a
shipped file cannot escape the manifest by being forgotten.

THE VERSION IS DERIVED FROM THE CONTENT, and that is deliberate. A hand-typed kit
version is a claim about the tree that nothing can test, so it drifts the moment
someone edits a shipped file and forgets the number. This one is a digest over
the manifest's own (path, sha256) pairs: it cannot be stale, and two trees with
the same version are the same kit by construction rather than by assertion.

Run:  python3 tools/kit_manifest.py            # regenerate registry/kit.json
      python3 tools/kit_manifest.py --check    # exit 1 naming every drifted file
Exit: 0 in agreement (or after a successful regenerate); 1 drift, each file named.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
KIT_ROOT = REPO / "TEMPLATE"
MANIFEST = REPO / "registry" / "kit.json"

# Transient artifacts, never part of the kit: a lock file, byte-code caches and
# pytest's own cache directory. Named as DIRECTORIES where they are directories,
# because a name match on a file would miss the tree beneath it.
EXCLUDED_DIRS = frozenset({"__pycache__", ".pytest_cache"})
EXCLUDED_FILES = frozenset({".audit.lock"})
EXCLUDED_SUFFIXES = (".pyc", ".pyo")

NOTE = (
    "Reference manifest of the shipped kit: every file under TEMPLATE/, with its "
    "sha256. GENERATED by tools/kit_manifest.py -- never hand-edited, because a "
    "hand-kept list of shipped files is a second copy of the tree that goes stale "
    "silently. `kit_version` is a digest over the manifest's own (path, sha256) "
    "pairs, so it cannot describe a tree other than the one it was computed from. "
    "Transient artifacts (__pycache__, .pytest_cache, .audit.lock, *.pyc) are "
    "excluded: they are build residue, not kit. Regenerate with "
    "`python3 tools/kit_manifest.py`; verify with `--check`, which names every "
    "drifted, missing and unlisted file."
)

def kit_paths() -> list[str]:
    """Every shipped file, repo-relative, sorted — the set the manifest describes."""
    out: list[str] = []
    for path in KIT_ROOT.rglob("*"):
        if not path.is_file():
            continue
        if any(part in EXCLUDED_DIRS for part in path.parts):
            continue
        if path.name in EXCLUDED_FILES or path.suffix in EXCLUDED_SUFFIXES:
            continue
        out.append(str(path.relative_to(REPO)))
    return sorted(out)

def digest(rel: str) -> str:
    """The sha256 of one shipped file, read in chunks so a large one never loads whole."""
    h = hashlib.sha256()
    with open(REPO / rel, "rb") as fh:
        for block in iter(lambda: fh.read(65536), b""):
            h.update(block)
    return h.hexdigest()

def kit_version(files: dict[str, str]) -> str:
    """A digest over the manifest's own pairs — a version that cannot be stale.

    Built from the SORTED (path, sha256) pairs with an explicit separator, so two
    different trees cannot produce the same digest by concatenation ambiguity.
    """
    h = hashlib.sha256()
    for rel, sha in sorted(files.items()):
        h.update(f"{rel}\0{sha}\n".encode())
    return h.hexdigest()[:12]

def build() -> dict:
    files = {rel: digest(rel) for rel in kit_paths()}
    return {
        "_note": NOTE,
        "kit_version": kit_version(files),
        "file_count": len(files),
        "files": files,
    }

def compare(current: dict, declared: dict) -> tuple[list[str], list[str], list[str]]:
    """(changed, missing, unlisted) — three DIFFERENT facts, never folded together.

    A file whose bytes moved is a port; a file the manifest names but the tree does
    not carry is a deletion; a file the tree carries but the manifest does not name
    is one that ESCAPED the manifest. The last is the one a hand-kept list would
    hide, which is why it is a failure rather than a note.
    """
    cur, dec = current.get("files") or {}, declared.get("files") or {}
    changed = sorted(rel for rel in dec if rel in cur and cur[rel] != dec[rel])
    missing = sorted(rel for rel in dec if rel not in cur)
    unlisted = sorted(rel for rel in cur if rel not in dec)
    return changed, missing, unlisted

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check", action="store_true",
        help="verify the tree against the manifest instead of regenerating it",
    )
    args = parser.parse_args(argv)

    if not KIT_ROOT.is_dir():
        print(
            f"kit manifest: {KIT_ROOT} does not exist — there is no shipped kit in this "
            "tree, so there is nothing to describe. A bootstrapped factory lands here."
        )
        return 0

    current = build()

    if not args.check:
        MANIFEST.parent.mkdir(parents=True, exist_ok=True)
        MANIFEST.write_text(json.dumps(current, indent=2, ensure_ascii=False) + "\n",
                            encoding="utf-8")
        print(f"kit manifest written: {MANIFEST.relative_to(REPO)} — "
              f"{current['file_count']} file(s), kit_version {current['kit_version']}")
        return 0

    if not MANIFEST.is_file():
        print(f"kit manifest: {MANIFEST.relative_to(REPO)} is absent — regenerate it with "
              "`python3 tools/kit_manifest.py`")
        return 1

    declared = json.loads(MANIFEST.read_text(encoding="utf-8"))
    changed, missing, unlisted = compare(current, declared)

    for rel in changed:
        print(f"  DRIFTED   {rel} — {declared['files'][rel][:12]} -> {current['files'][rel][:12]}")
    for rel in missing:
        print(f"  MISSING   {rel} — named by the manifest, absent from the tree")
    for rel in unlisted:
        print(f"  UNLISTED  {rel} — in the tree but not in the manifest (escaped it)")

    if changed or missing or unlisted:
        print(f"kit manifest DRIFTED: {len(changed)} changed, {len(missing)} missing, "
              f"{len(unlisted)} unlisted — regenerate with `python3 tools/kit_manifest.py`")
        return 1

    print(f"kit manifest in agreement: {current['file_count']} file(s), "
          f"kit_version {declared.get('kit_version')}")
    return 0

if __name__ == "__main__":
    sys.exit(main())
